config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#main'
  resources :states, param: :states do
    post :choose, on: :collection
  end
end

app/models/chart.rb
require 'SVG/Graph/TimeSeries'

class Chart
  # Expected input:
  # {legend_a => [[date_a1, value_a1], [date_a2, value_a2]...], legend_b => [[...]], ...}
  def initialize(hash)
    @data = hash.transform_values &:sort
  end

  def to_graph
    @graph ||= SVG::Graph::TimeSeries.new({
      height: 600,
      width: 800,
      x_label_format: '%d %b',
      number_format: '%d',
      add_popups: true,
      popup_format: '%d %b %Y',
      min_y_value: 0,
      scale_y_divisions: divisions,
      inline_style_sheet: '/* */'
    }).tap do |graph|
      data.each do |legend, pairs|
        graph.add_data data: pairs.map {|(date, value)| [date.to_time, value] }.flatten, title: legend.to_s
      end
    end
  end

  private

  attr_reader :data

  def series
    @series ||= @data.values
  end

  def values
    @values ||= series.map {|single_series| single_series.map &:last }
  end

  def max_value
    @max_value ||= values.flatten.max
  end

  def divisions
    @divisions ||= max_value.nil? ? 10 : [max_value.ceil(-Math.log10(max_value)) / 10, 10].max
  end
end

app/models/dataset.rb
class Dataset

  attr_reader :legend

  def initialize(pairs:, legend:)
    @pairs = pairs.sort
    @legend = legend
  end

  def pairs
    @pairs.sort
  end

  def dates
    @dates ||= pairs.map &:first
  end

  def values
    @values ||= pairs.map &:last
  end

  def max_value
    @max_value ||= values.map(&:to_i).max
  end

  def min_date
    @min_date ||= dates.first
  end

  def max_date
    @max_date ||= dates.last
  end
end

app/models/query.rb
class Query
  attr_reader :client

  def initialize(states:, date_range:, client: StateDaily)
    @states = states
    @date_range = date_range
    @client = client
  end

  def raw_data
    @raw_data ||= @states.to_h {|state| [state, client.new(state: state, date: @date_range).fetch!] }
  end
end

app/models/state.rb
class State
  attr_reader :abbr, :name

  def initialize(abbr:, name:)
    @abbr = abbr
    @name = name
  end

  def to_s
    name
  end

  class << self
    def all
      states.values
    end

    def find(abbr)
      abbr.kind_of?(Array) ? abbr.map {|element| State.find element }.compact : states[normalize abbr]
    end

    private

    def normalize(string)
      string.to_s.upcase
    end

    def states
      @states ||= Hash[CS.states(:us).map {|abbr, name| [normalize(abbr), new(abbr: normalize(abbr), name: name)] } ].with_indifferent_access
    end

    private :new
  end
end

app/models/state_daily.rb
class StateDaily
  def initialize(state:, date:)
    @state = state
    @date = date
  end

  # TODO: now that we don't need this method except for testing, should we get rid of it and test through request instead?
  def url
    @url ||= date_range? ? individuals.map(&:url) : request.url
  end

  def request
    @request ||= if date_range?
      Typhoeus::Hydra.new.tap do |hydra|
        individuals.each {|individual| hydra.queue individual.request }
      end
    else
      Typhoeus::Request.new "https://api.covidtracking.com/v1/states/#{@state.abbr.downcase}/#{@date.to_s :number}.json", cache_ttl: 6.hours.to_i
    end
  end

  def fetch!
    if date_range?
      hydra = request
      requests = hydra.queued_requests.dup
      hydra.run
      requests.map do |request|
        if request.response.success?
          response = JSON.parse request.response.body
          response['date'].nil? ? nil : [request.url, response]
        end
      end.compact
    else
      [request.url, JSON.parse(request.run.body)]
    end
  end

  private

  def date_range?
    @date.kind_of? Range
  end

  def individuals
    @individuals ||= @date.map {|date| self.class.new state: @state, date: date }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_gettext_locale
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def show
    normalize_states

    @states = State.find params[:states]
    @date = Date.current
    date_range = (@date - 29.days)..@date

    query = Query.new states: @states, date_range: date_range
    @raw_data = query.raw_data
  end

  def choose
    redirect_to action: :show, states: Array(params[:states]).join(',').downcase
  end

  private

  def normalize_states
    params[:states] = params[:states].strip.downcase.split(%r{\W+})
    state_abbrs = params[:states]
    sorted_abbrs = state_abbrs.sort
    unless sorted_abbrs == state_abbrs
      redirect_to action: :show, states: sorted_abbrs.join(','), status: :moved_permanently and return
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def main
    #
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= [strip_tags(content_for :page_title), _('COVID-19 Tracking Charts')].compact.join ' | '
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :extra_headers
  %body
    %header
      %h1
        = link_to '/' do
          = h(_ '%{span}COVID-19%{_span} Tracking Charts by U.S. State') % {span: '<span class="accent">'.html_safe, _span: '</span>'.html_safe}
    %nav= cell(:state_selector, @states, url: choose_states_path)

    %main
      - if content_for :page_title
        %h1= content_for :page_title
      = yield

    %footer
      %p= _('Version %{app_version}, released %{release_date}.') % {app_version: APP_VERSION, release_date: RELEASE_DATE.strftime('%-d %B %Y')}

      :markdown
        #{_ 'Developed by [Marnen E. Laibow-Koser](http://www.marnen.org). Lend a hand at [https://github.com/marnen/covid_tracking_charts](https://github.com/marnen/covid_tracking_charts)!'}

        #{_ 'Data from [The COVID Tracking Project](https://covidtracking.com/).'}

app/views/states/show.html.haml
- content_for :extra_headers do
  = stylesheet_link_tag 'chart'

- content_for :page_title do
  = cell 'state_list', @states

:markdown
  #{_ 'This chart shows the *daily cumulative total* number of individuals who have tested positive for coronavirus.'}

= cell('chart', @raw_data).call

%details
  %summary= _ 'Raw data'
  - @raw_data.each do |state, requests|
    = cell('state_requests', {state: state, requests: requests}).call

app/views/welcome/main.html.haml
- content_for :page_title do
  Welcome!

.welcome
  :markdown
    #{_ 'This project is a work in progress! I created it because there didn’t seem to be a source of time series charts showing the number of novel coronavirus cases per day *for each U.S. state*. This site provides easy access to such charts, showing the last 30 days of data (or whatever’s available if it’s less than 30 days); the data is courtesy of the wonderful [COVID Tracking Project](https://covidtracking.com/).'}

    #{_ 'My aim is for this site to be easy to use and accessible to all users, including visually impaired users and those without JavaScript support. If you have a feature request, or if you’d like to contribute code or otherwise collaborate, please feel free to file an issue at our [GitHub repository](https://github.com/marnen/covid_tracking_charts).'}
    
    **#{_ 'Note:'}** #{_ 'This application is temporarily nonfunctional because the [COVID Tracking Project](https://covidtracking.com) is no longer providing a data feed. We thank the COVID Tracking Project for all their work and hope to find a new data feed so we can continue running this application. Please see https://github.com/marnen/covid_tracking_charts/issues/79 for updates on that.'}

  %p
    = _ 'I hope you find this project useful!'
    %br
    %span.signature= link_to _('—Marnen E. Laibow-Koser'), 'http://www.marnen.org'